/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pokemon.test.vjeza;

import java.awt.Color;
import java.sql.*;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.*;
import net.proteanit.sql.DbUtils;

public class BorbaPokemona extends javax.swing.JFrame {

    Connection conn;
    PreparedStatement pst;
    ResultSet rs;
    JFrame f = new JFrame();
    int broj = 0;
    ArrayList id_pok = new ArrayList<>();
    ArrayList id_arena = new ArrayList<>();
    ArrayList<String> id_bor = new ArrayList<>();
    
    public BorbaPokemona() {
        initComponents();
        conn = JavaConnect.connectDb();
        LoadBorba();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDialog1.setMaximumSize(new java.awt.Dimension(500, 350));
        jDialog1.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialog1.setModal(true);

        jRadioButton1.setText("Pokemon A");

        jRadioButton2.setText("Pokemon B");

        jLabel1.setText("Datum(YYYY-MM-DD)");

        jLabel2.setText("Vrijeme(HH-MM-SS)");

        jButton3.setText("Odustani");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Unesi");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        jDialog2.setMinimumSize(new java.awt.Dimension(500, 350));
        jDialog2.setModal(true);

        jButton5.setText("Odustani");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Obriši");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(52, 52, 52))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Datum i Vrijeme", "Pokemon_A", "Pokemon_B", "Arena"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Nova Borba");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Obriši");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String sql1;
        String sql2;
        
        sql1 = "Select PokemonId, Naziv from pokemon.pokemon";
        sql2 = "Select ArenaId, Naziv from pokemon.arena";
        
        try{
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            
            while(rs.next()){
                if(!id_pok.contains(rs.getString(1))){
                jComboBox1.addItem(rs.getString(2));
                jComboBox2.addItem(rs.getString(2));
                id_pok.add(rs.getString(1));
                }
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(f, e);
            System.out.println(e);
        }
        
        try{
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            
            while(rs.next()){
                if(!id_arena.contains(rs.getString(1))){
                jComboBox3.addItem(rs.getString(2));
                id_arena.add(rs.getString(1));
                }
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(f, e);
            System.out.println(e);
        }
        
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
        jComboBox3.setSelectedIndex(-1);
        
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jLabel3.setForeground(Color.black);
        jLabel4.setForeground(Color.black);
        jLabel5.setForeground(Color.black);
        jLabel1.setForeground(Color.black);
        jLabel2.setForeground(Color.black);
        jLabel6.setForeground(Color.black);
        if(jRadioButton1.isSelected() && jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(f, "Odaberite jednog ponjednika");
            jLabel3.setForeground(Color.red);
        }else if(!jRadioButton1.isSelected() && !jRadioButton2.isSelected()){
            JOptionPane.showMessageDialog(f, "Odaberite jednog ponjednika");
            jLabel3.setForeground(Color.red);
        }
        if(jComboBox1.getSelectedIndex() == -1 && jComboBox2.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(f, "Odaberite pokemone koji se bore");
            jLabel4.setForeground(Color.red);
            jLabel5.setForeground(Color.red);
        }else if(jComboBox1.getSelectedIndex() != -1 && jComboBox2.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(f, "Odaberite pokemona B");
            jLabel4.setForeground(Color.red);
            //jLabel5.setForeground(Color.red);
        }else if(jComboBox1.getSelectedIndex() == -1 && jComboBox2.getSelectedIndex() != -1){
            JOptionPane.showMessageDialog(f, "Odaberite pokemona A");
            jLabel5.setForeground(Color.red);
            //jLabel5.setForeground(Color.red);
        }if(jTextField1.getText().trim().isEmpty() && jTextField2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(f, "Upišite Datum i vrijeme borbe");
            jLabel1.setForeground(Color.red);
            jLabel2.setForeground(Color.red);
        }else if(!jTextField1.getText().trim().isEmpty() && jTextField2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(f, "Upišite vrijeme brobe");
            //jLabel1.setForeground(Color.red);
            jLabel2.setForeground(Color.red);
        }else if(!jTextField2.getText().trim().isEmpty() && jTextField1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(f, "Upišite Datum brobe");
            //jLabel1.setForeground(Color.red);
            jLabel1.setForeground(Color.red);
        }if(jComboBox3.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(f, "Odaberite arenu brobe");
            //jLabel1.setForeground(Color.red);
            jLabel6.setForeground(Color.red);
        }
        
        String sql = "Insert into borba (BorbaId, Pokemon1Id, Pokemon2Id, PokemonPobjednikId, DatumVrijemeBorbe, ArenaId) values (?, ?, ?, ?, ?, ?)";
        String id_pob;
        
        try{
            
            pst=conn.prepareStatement(sql);
            pst.setInt(1, broj + 1);
            pst.setString(2, id_pok.get(jComboBox1.getSelectedIndex()+1).toString());
            pst.setString(3, id_pok.get(jComboBox2.getSelectedIndex()+1).toString());
            if(jRadioButton1.isSelected()){
                pst.setString(4, id_pok.get(jComboBox1.getSelectedIndex()+1).toString());
                pst.setString(5, jTextField1.getText() + " " + jTextField2.getText());
                pst.setString(6, id_arena.get(jComboBox3.getSelectedIndex()+1).toString());
                pst.execute();
                JOptionPane.showMessageDialog(f, "Nova borba uspjesno stvorena!");
                pst.close();
            }else if (jRadioButton2.isSelected()){
                pst.setString(4, id_pok.get(jComboBox2.getSelectedIndex()+1).toString());
                pst.setString(5, jTextField1.getText() + " " + jTextField2.getText());
                pst.setString(6, id_arena.get(jComboBox3.getSelectedIndex()+1).toString());
                pst.execute();
                JOptionPane.showMessageDialog(f, "Nova borba uspjesno stvorena!");
                pst.close();
            }
            //pst.setString(4, id_index);
            //pst.setString(5, jTextField3.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(f, e);
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        LoadBorba();
        jDialog1.setVisible(false);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String sql = "Select BorbaId, DatumVrijemeBorbe from pokemon.borba";
        
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while(rs.next()){
                if(!id_bor.contains(rs.getString(1))){
                jComboBox4.addItem(rs.getString(2));
                id_bor.add(rs.getString(1));
                }
            }
            
            pst.close();
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(f, e);
            System.out.println(e);
        }
        
        jDialog2.setVisible(true);
        jDialog2.setLocationRelativeTo(null);
        jComboBox4.setSelectedIndex(-1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String bris = id_bor.get(jComboBox4.getSelectedIndex());
        String sql = "DELETE FROM pokemon.borba WHERE BorbaId = " + bris + ";";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.execute();
            
            
            pst.close();
            JOptionPane.showMessageDialog(f, "Uspješno izbrisano");
        }catch(Exception e){
            JOptionPane.showMessageDialog(f, e);
            System.out.println(e);
        }
        
        LoadBorba();
        jDialog2.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        LoadBorba();
        jDialog2.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorbaPokemona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorbaPokemona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorbaPokemona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorbaPokemona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorbaPokemona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void LoadBorba() {
        String sql;
        sql = "SELECT b.DatumVrijemeBorbe AS Datum_i_vrijeme, p1.Naziv AS Pokemon_A, p2.Naziv AS Pokemon_B, a.Naziv AS Arena "
                            + "FROM pokemon.borba AS b "
                            + "LEFT JOIN pokemon.pokemon AS p1 ON b.Pokemon1Id = p1.PokemonId "
                            + "LEFT JOIN pokemon.pokemon AS p2 ON b.Pokemon2Id = p2.PokemonId "
                            + "LEFT JOIN pokemon.arena AS a ON b.ArenaId = a.ArenaId";
        
       try{
           pst = conn.prepareStatement(sql);
           rs = pst.executeQuery();
           
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
           rs.close();
           
           rs = pst.executeQuery();
           
           while(rs.next()){
               broj++;
           }
           
           pst.close();
           rs.close();
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(f, e);
           System.out.println(e);
       }
    }
}
